### ISSUE TITLE
Create links to Satellite Events.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#10]
From the calendar view, create links to the satellite events:

- DLfM: https://dlfm.web.ox.ac.uk/2020-programme
- NLP4MusA: https://sites.google.com/view/nlp4musa
- HAMR: https://ismir.github.io/ISMIR2020/hamr/

**Comment by evansavage** [comment]
I just pushed changes for this to dev and production

**Comment by vigliensoni** [comment]
@evansavage See note in the commit.
