### ISSUE TITLE
Link tutorial info to tutorial anchor.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#14]
When pressing the “Info” button on any tutorial from [https://program.ismir2020.org/tutorials.html](https://program.ismir2020.org/tutorials.html), the link should include the tutorial anchor in the page [https://ismir2020.org/tutorials/](https://ismir2020.org/tutorials/), so that we land in the right tutorial.

**Comment by evansavage** [comment]
Do we need the info button on the https://program.ismir2020.org/tutorials.html page if you are already looking at the available info? Can I just remove that button and move the text from the https://ismir2020.org/tutorials/ page?

**Comment by vigliensoni** [comment]
If there's no additional, meaningful information, there's no need to have the info button.

**Comment by evansavage** [comment]
I think this is settled now, yes?
