### ISSUE TITLE
Remove "Links" menu button from LBD.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#15]
Unless @ChristianFrisson has a specific use for this meny, there is no need for having this button and we should remove it.

<img width="1230" alt="Screen Shot 2020-10-08 at 3 21 49 PM" src="https://user-images.githubusercontent.com/492229/95503892-fe797e80-0979-11eb-984c-55922df2c7a4.png">

**Comment by evansavage** [comment]
Just removed, should be reflected soon.

**Comment by ChristianFrisson** [comment]
Actually I was planning on adding links when mentioned in LBD papers (such as github repositories).

**Comment by ChristianFrisson** [comment]
I see that links are not available for other tracks either, let's keep it that way! Closing.
