### ISSUE TITLE
Center weekly calendar to start at 7 am.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#2]
After a person chooses their timezone, the calendar should display the day starting at their local 7 am.

The current behaviour displays the calendar starting at midnight.

This arrangement may not be ideal for people in Asia, which will start in the evening the day before. Can we arrange something different in this case?

**Comment by evansavage** [comment]
If dates are displayed starting at 7 AM, some time zones will truncate a portion of the events. Maybe instead we could do a dynamic color coding for the events that happen across the daytime hours?

**Comment by vigliensoni** [comment]
The calendar view should be optimized according to the user's declared city/timezone.

**Comment by evansavage** [comment]
Will close for now barring any edge cases my implementation does not work for.
