### ISSUE TITLE
Honorific title in Johanna Devaney's name

### ISSUE THREAD

**Issue by napulen** [DDMAL/ISMIR-Conf#20]
It was suggested today that the honorific title `Dr.` should be used in Johanna Devaney's keynote description, in order to be consistent with the ISMIR keynote. More specifically, `Johanna Devaney` -> `Dr. Johanna Devaney`.

**Comment by ChristianFrisson** [comment]
Done: 1d326d7be3415a55859ca909bb70376b70ca7d14
