### ISSUE TITLE
Change name of music piece.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#21]
Hi @evansavage , could your please amend the name of the piece at 

https://program.ismir2020.net/music_415.html to 

“The Pulse of The Sunrise: The Voice of Santur with Audience Participation”

**Comment by evansavage** [comment]
Yes I am updating now. You mentioned that you wanted an updated message to take the place of the music videos that have been removed. Right now I have, **The artist has decided to remove their composition from the website.** It's a little heavy-handed, but is that ok?

**Comment by vigliensoni** [comment]
I think it's better something lighter like **The composition was available for listening during the conference only.**

**Comment by evansavage** [comment]
Ok it is now updated

**Comment by santurista** [comment]
Hi Evan, thank you for updating / merging the paper title and the composition.
Just to add that I would be very happy to keep my video on ISMIR website, just that at the time that I received the login information, I could not log in and Gove my consent about the video.
