### ISSUE TITLE
Create session view.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#4]
After clicking on a specific session on the calendar, we should land to a _**session**_ view. The list of all papers+authors for the specific session should be rendered. 

Each paper in the list should be linked to a paper view **AND** to the Slack channel where the live discussion is happening.

@finn42, or whoever is going to be in charge of creating the poster channels on Slack, should provide the links.

**Comment by evansavage** [comment]
Does the link from the Schedule to the Paper search not already do what you are requesting? The session titles are incorrect currently. Once they are corrected, a click on a session on the schedule will lead to a search in the 'Papers' tab, filtered by the session that was clicked, rendering all the papers from the relevant session.
