### ISSUE TITLE
Generate PNGs for each paper.

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#5]
Any news about the PNG of figures or tables for each paper, @caitlin-hutnyk?

We need to add these images to the paper snippets.

We currently see this:

![Screen Shot 2020-09-18 at 2 31 13 PM](https://user-images.githubusercontent.com/492229/93632620-9c051200-f9bb-11ea-9417-a854df8ba4cb.png)

**Comment by vigliensoni** [comment]
@caitlin-hutnyk check instructions here:

https://github.com/DDMAL/ISMIR-Conf/blob/master/scripts/README.md

And this repo:

https://github.com/Mini-Conf/image-extraction

**Comment by vigliensoni** [comment]
Another tool for this:

https://github.com/allenai/pdffigures2

**Comment by vigliensoni** [comment]
Cropping all papers by hand should take two hours, and so don't spend more time than that.

**Comment by caitlin-hutnyk** [comment]
I've written my own implementation which works relatively well, but it can only extract images which are embedded as an image file type and not as a native figure. I'm taking a look at the ISMIR-Conf implementation now to see if it works better

**Comment by vigliensoni** [comment]
Great. Please consider manually cropping an image for each paper should take ~2 hours (i.e., one minute per paper, at the most), and so you should not spend more time than this.

**Comment by vigliensoni** [comment]
@caitlin-hutnyk I can see images already on the site. Are all of them in the system? If so, close the issue, please.
