### ISSUE TITLE
Make all paper zone linkable. 

### ISSUE THREAD

**Issue by vigliensoni** [DDMAL/ISMIR-Conf#8]
When browsing paper, make all the zone linkable to the corresponding paper, not just the title.
<img width="408" alt="Screen Shot 2020-09-25 at 2 57 34 PM" src="https://user-images.githubusercontent.com/492229/94305610-7342c680-ff3f-11ea-9e32-bc73a9abfe72.png">

**Comment by evansavage** [comment]
I have added a link to the page from the image as well, and now there is a slack channel link at the bottom, too. Review these changes on the development site. http://ddmal.music.mcgill.ca/ISMIR-Conf/papers.html?filter=keywords

**Comment by vigliensoni** [comment]
Why don't you add the `href` to the `div` containing the card?

Also, I don't happen to see the Slack channel link now.

![Screen Shot 2020-10-08 at 3 06 25 PM](https://user-images.githubusercontent.com/492229/95502450-dbe66600-0977-11eb-91bb-8dbf46a91eb6.png)

**Comment by evansavage** [comment]
I misunderstood what Finn wanted for the slack links, the code is still there, they are just turned off at their request.

**Comment by vigliensoni** [comment]
Yeah, I saw the links briefly. In case they go live, they should be centered in the card instead of justified to the right.

**Comment by evansavage** [comment]
I fixed this, should be reflected soon.
